package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.connectivity.ConnectivityPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin connectivity_plus, dev.fluttercommunity.plus.connectivity.ConnectivityPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.analytics.FlutterFirebaseAnalyticsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin firebase_analytics, io.flutter.plugins.firebase.analytics.FlutterFirebaseAnalyticsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin firebase_core, io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin integration_test, dev.flutter.plugins.integration_test.IntegrationTestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_event_analytics.QsEventAnalyticsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_event_analytics, com.example.qs_event_analytics.QsEventAnalyticsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_ip_location.QsIpLocationPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_ip_location, com.example.qs_ip_location.QsIpLocationPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_log.QsLogPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_log, com.example.qs_log.QsLogPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_net_request.QsNetRequestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_net_request, com.example.qs_net_request.QsNetRequestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.qs_toast.QsToastPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin qs_toast, com.example.qs_toast.QsToastPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin shared_preferences_android, io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin sqflite_android, com.tekartik.sqflite.SqflitePlugin", e);
    }
  }
}
